import type { CognitivePhase } from "@/features/cognitive/domain/types";

export interface PhaseLesson {
  readonly phase: CognitivePhase;
  readonly label: string;
  readonly shortLabel: string;
  readonly group: "Understand" | "Decide" | "Execute" | "Improve";
  readonly purpose: string;
  readonly input: string;
  readonly output: string;
  readonly source: string;
  readonly persistence: string;
}

export const PHASE_LESSONS: readonly PhaseLesson[] = [
  {
    phase: "CUE",
    label: "Receive cue",
    shortLabel: "Cue",
    group: "Understand",
    purpose: "Turn an external event into a durable, deduplicated unit of work.",
    input: "Webhook, schedule, user action, or assistant request.",
    output: "A cue linked to a new cognitive session.",
    source: "persistence/postgres/transactions/ingest-cue.ts",
    persistence: "cues · cognitive_sessions · idempotency_records",
  },
  {
    phase: "PERCEIVE",
    label: "Perceive facts",
    shortLabel: "Perceive",
    group: "Understand",
    purpose: "Translate the cue into bounded facts and an authoritative target.",
    input: "Persisted cue and its structured payload.",
    output: "A reusable perception snapshot for this evaluation generation.",
    source: "orchestration/cognitive-loop-driver.ts",
    persistence: "authoritative_perception_snapshots",
  },
  {
    phase: "BUILD_CONTEXT",
    label: "Build context",
    shortLabel: "Context",
    group: "Understand",
    purpose: "Assemble only the information the current decision is allowed to use.",
    input: "Cue, perception snapshot, session, and target specification.",
    output: "A bounded cognitive context with security assertions.",
    source: "orchestration/context-assembler.ts",
    persistence: "No hidden scratchpad is persisted.",
  },
  {
    phase: "RETRIEVE_MEMORY",
    label: "Retrieve memory",
    shortLabel: "Memory",
    group: "Understand",
    purpose: "Load relevant knowledge that previously crossed a verified boundary.",
    input: "Memory kind and key requests from the current context.",
    output: "Verified memory heads and their evidence references.",
    source: "orchestration/memory-retrieval-orchestrator.ts",
    persistence: "verified_memory · verified_memory_heads",
  },
  {
    phase: "GENERATE_CANDIDATES",
    label: "Generate candidates",
    shortLabel: "Generate",
    group: "Decide",
    purpose: "Propose possible actions without granting permission to perform them.",
    input: "Secured context and verified memory.",
    output: "Candidate actions bound to the current cue and generation.",
    source: "orchestration/gemini-candidate-generator.ts",
    persistence: "candidate_actions · candidate_evidence",
  },
  {
    phase: "SCORE",
    label: "Score candidates",
    shortLabel: "Score",
    group: "Decide",
    purpose: "Rank candidates using confidence, utility, risk, and cost.",
    input: "Candidate estimates and the versioned scoring formula.",
    output: "Ignore, ask a human, or continue as an auto-candidate.",
    source: "orchestration/candidate-ranking.ts",
    persistence: "Score snapshot on candidate_actions",
  },
  {
    phase: "GROUND_VERIFY",
    label: "Ground in evidence",
    shortLabel: "Ground",
    group: "Decide",
    purpose: "Require real, current evidence before policy can consider execution.",
    input: "Top candidate, target facts, and evidence references.",
    output: "Verified, insufficient, or conflicting grounding result.",
    source: "orchestration/github-grounding-policy.ts",
    persistence: "evidence_records · grounding_results",
  },
  {
    phase: "POLICY_SAFETY",
    label: "Apply policy",
    shortLabel: "Policy",
    group: "Decide",
    purpose: "Decide whether a grounded candidate is allowed, denied, or needs review.",
    input: "Candidate plus verified grounding provenance.",
    output: "Policy decision and a fresh, scoped runtime authorization when allowed.",
    source: "orchestration/authorization-orchestrator.ts",
    persistence: "policy_decisions · execution_safety_events",
  },
  {
    phase: "PLAN",
    label: "Build plan",
    shortLabel: "Plan",
    group: "Execute",
    purpose: "Convert the authorized goal into immutable ordered steps.",
    input: "Authorized candidate and secured context.",
    output: "A versioned action plan with dependencies.",
    source: "api/runtime-composition.ts",
    persistence: "action_plans · action_plan_steps",
  },
  {
    phase: "DURABLE_EXECUTION",
    label: "Prepare execution",
    shortLabel: "Prepare",
    group: "Execute",
    purpose: "Reserve durable execution state before any provider call can happen.",
    input: "Plan and live authorization bound to the current safety generation.",
    output: "Execution, step, and logical operation records.",
    source: "orchestration/execution-preparation-orchestrator.ts",
    persistence: "executions · execution_step_state · execution_operations",
  },
  {
    phase: "ACT",
    label: "Dispatch action",
    shortLabel: "Act",
    group: "Execute",
    purpose: "Perform the allowed operation through a capability-limited adapter.",
    input: "Authorized operation request and idempotency fingerprint.",
    output: "A factual provider outcome or bounded failure.",
    source: "orchestration/dispatch-orchestrator.ts",
    persistence: "execution_operation_attempts · execution_events",
  },
  {
    phase: "OBSERVE",
    label: "Record observation",
    shortLabel: "Observe",
    group: "Execute",
    purpose: "Sanitize and record what the provider actually returned.",
    input: "Adapter result and provider metadata.",
    output: "Immutable observation evidence.",
    source: "orchestration/observation-orchestrator.ts",
    persistence: "observations",
  },
  {
    phase: "VERIFY_RESULT",
    label: "Verify result",
    shortLabel: "Verify",
    group: "Execute",
    purpose: "Compare observed facts with the plan's expected result.",
    input: "Canonical observation set and verifier version.",
    output: "Verified, failed, or inconclusive result.",
    source: "orchestration/verification-orchestrator.ts",
    persistence: "result_verifications · result_verification_observations",
  },
  {
    phase: "REWARD",
    label: "Apply reward",
    shortLabel: "Reward",
    group: "Improve",
    purpose: "Turn the verified outcome into an immutable learning signal.",
    input: "Execution-bound verification and reward rule.",
    output: "A deduplicated positive, neutral, or negative reward event.",
    source: "orchestration/reward-orchestrator.ts",
    persistence: "reward_events",
  },
  {
    phase: "LEARN",
    label: "Update learning",
    shortLabel: "Learn",
    group: "Improve",
    purpose: "Update the skill projection from the append-only reward ledger.",
    input: "New reward event for a skill key.",
    output: "Updated confidence, total reward, and sample count.",
    source: "persistence/postgres/repositories/learning-repository.ts",
    persistence: "learning_state",
  },
  {
    phase: "SAVE_MEMORY",
    label: "Save verified memory",
    shortLabel: "Remember",
    group: "Improve",
    purpose: "Admit long-term memory only when supported by verified evidence.",
    input: "Verified result and bounded memory proposal.",
    output: "Immutable memory version and updated head pointer.",
    source: "orchestration/memory-orchestrator.ts",
    persistence: "verified_memory · verified_memory_sources · verified_memory_heads",
  },
  {
    phase: "CLEAR_WORKING_MEMORY",
    label: "Clear temporary state",
    shortLabel: "Clear",
    group: "Improve",
    purpose: "Discard temporary assumptions so they cannot become authority later.",
    input: "Completed cognitive generation.",
    output: "Only explicit durable facts remain.",
    source: "orchestration/cognitive-loop-driver.ts",
    persistence: "Working memory is intentionally not stored.",
  },
  {
    phase: "COOLDOWN",
    label: "Wait safely",
    shortLabel: "Cooldown",
    group: "Improve",
    purpose: "Delay a permitted retry and prevent uncontrolled rapid repetition.",
    input: "Recoverable failure and remaining retry budget.",
    output: "A durable resume deadline or human escalation.",
    source: "orchestration/recovery-orchestrator.ts",
    persistence: "cognitive_sessions · failure_audit_events",
  },
  {
    phase: "HUMAN_REVIEW",
    label: "Request human review",
    shortLabel: "Review",
    group: "Improve",
    purpose: "Stop autonomy when evidence, policy, or recovery requires a person.",
    input: "Review reason and correlated decision artifacts.",
    output: "A fail-closed session boundary.",
    source: "domain/human-escalation.ts",
    persistence: "cognitive_sessions · execution_safety_state",
  },
  {
    phase: "IDLE",
    label: "Return to idle",
    shortLabel: "Idle",
    group: "Improve",
    purpose: "Mark the cycle complete and prevent an old cue from running twice.",
    input: "Completed cleanup and durable outcome.",
    output: "A finished session ready for inspection and replay.",
    source: "api/runtime-composition.ts",
    persistence: "cognitive_sessions",
  },
];

export const PHASE_INDEX = new Map(
  PHASE_LESSONS.map((lesson, index) => [lesson.phase, index]),
);
